"""Sprint_1_2_Nucleo_Financeiro

Revision ID: 19506ee50a66
Revises: 38253abe6bdf
Create Date: 2026-07-13 12:20:27.550143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19506ee50a66'
down_revision = '38253abe6bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operacoes',
    sa.Column('numero_operacao', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fabrica_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('data_operacao', sa.Date(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['fabrica_id'], ['fabricas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_operacao')
    )
    op.create_table('boletos',
    sa.Column('operacao_id', sa.Integer(), nullable=False),
    sa.Column('numero_boleto', sa.String(length=50), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('valor_compra', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('percentual_comissao', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('juros', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taxa_cobranca', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_repasse', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_prevista_recebimento', sa.Date(), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_pagar_colaborador',
    sa.Column('operacao_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_receber',
    sa.Column('boleto_id', sa.Integer(), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('valor_comissao', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boleto_id'], ['boletos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aportes', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aportes', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.drop_table('contas_receber')
    op.drop_table('contas_pagar_colaborador')
    op.drop_table('boletos')
    op.drop_table('operacoes')
    # ### end Alembic commands ###
